version: '3.8'
services:
  aservice:
    build: AService
    environment:
    - ASPNETCORE_URLS="https://+;http://+"
    - ASPNETCORE_HTTPS_PORT=8001
    - ASPNETCORE_Kestrel__Certificates__Default__Password="123456"
    - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
    - 8000:80
    - 8001:443 

  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local
